theme: jekyll-theme-hacker
title: Welcome to Mikey's website!
description: Feel free to bookmark this page and keep up to date on my projects!
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
